<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>adb224bf-dff7-4c66-9604-254a628b2a31</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CommunityHub.API\CommunityHub.API.csproj" />
    <ProjectReference Include="..\..\Gateway.API\Gateway.API.csproj" />
    <ProjectReference Include="..\..\UserService.GRpc\UserService.GRpc.csproj" />
  </ItemGroup>

</Project>
